name: cmake-build

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-24.04
        - os: macos-15
        - os: windows-2025
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Create Build Environment
      env:
        IDASDK_SECRET: ${{ secrets.IDASDK_SECRET }}
      working-directory: ${{ github.workspace }}
      shell: bash
      run: |
        mkdir -p "${{ runner.workspace }}/build"
        ./.github/scripts/decrypt_secret.sh
        unzip -q "${{ runner.workspace }}/build/idasdk91.zip" \
              -d "${{ runner.workspace }}/build/"
        unzip -q "${{ runner.workspace }}/build/idasdk_teams82.zip" \
              -d "${{ runner.workspace }}/build/"

    - name: Enable Developer Command Prompt (Windows)
      if: matrix.os == 'windows-2025'
      uses: ilammy/msvc-dev-cmd@v1.12.1

    - name: Enable mold linker (Linux)
      if: matrix.os == 'ubuntu-24.04'
      uses: rui314/setup-mold@v1

    - name: Setup CMake and Ninja
      uses: lukka/get-cmake@v4.0.2
      with:
        cmakeVersion: 4.0.2
        ninjaVersion: 1.12.1

    - name: Configure CMake (default build)
      working-directory: ${{ runner.workspace }}/build
      shell: bash
      run: |
        cmake "${{ github.workspace }}" -G Ninja \
          "-DCMAKE_BUILD_TYPE=${BUILD_TYPE}" \
          "-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" \
          "-DIdaSdk_ROOT_DIR=${{ runner.workspace }}/build/idasdk91"

    - name: Build (default)
      working-directory: ${{ runner.workspace }}/build
      shell: bash
      run: cmake --build . --config "${BUILD_TYPE}"

    - name: Test
      working-directory: ${{ runner.workspace }}/build
      shell: bash
      run: ctest --build-config "${BUILD_TYPE}" --output-on-failure -R '^[A-Z]'

    - name: Configure CMake (IDA Pro 8.x plugin build)
      working-directory: ${{ runner.workspace }}/build
      shell: bash
      run: |
        cmake "${{ github.workspace }}" -G Ninja \
          "-DCMAKE_BUILD_TYPE=${BUILD_TYPE}" \
          "-DIdaSdk_ROOT_DIR=${{ runner.workspace }}/build/idasdk_teams82" \
          "-DBINEXPORT_IDAPRO_PLUGIN_NAME_EXTRA_SUFIX=8"

    - name: Build (IDA Pro 8.x plugin build)
      working-directory: ${{ runner.workspace }}/build
      shell: bash
      run: |
        cmake --build . --config "${BUILD_TYPE}" \
          --target binexport12_ida8 binexport12_ida864

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BinExport-${{ runner.os }}
        path: |
          ${{ runner.workspace }}/build/binaryninja/binexport*
          ${{ runner.workspace }}/build/ida/binexport*
          ${{ runner.workspace }}/build/tools/binexport2dump*
